# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkmodel',
            name='Name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
