# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleSearch', '0002_auto_20171204_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkmodel',
            name='image',
            field=models.ImageField(default='False', upload_to='./media/'),
        ),
    ]
