# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='name',
            field=models.CharField(default='demo', max_length=255),
        ),
    ]
