# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demo', max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
