# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-29 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_test', '0002_auto_20171230_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
