# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-30 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171228_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademark',
            name='goodsand_services',
        ),
    ]
