# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-02 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_trademark_goodsand_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademark',
            name='Product',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trademark',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
